import { getSupabaseClient } from '../../shared/api/supabase';

export type PhaseSummary = {
  id: string; routeId: string; branchId: string | null; name: string; description: string | null;
  orderValue: number; startTime: string | null;
  status: 'planned' | 'current' | 'completed' | 'skipped' | 'cancelled'; isDefault: boolean;
};
export type CreatePhaseInput = { name: string; description?: string; startTime?: string | null };
export type UpdatePhaseInput = CreatePhaseInput;
type PhaseRow = { id:string; route_id:string; branch_id:string|null; name:string; description:string|null; order_value:number|string; start_time:string|null; status:PhaseSummary['status']; is_default:boolean };
const phaseColumns='id, route_id, branch_id, name, description, order_value, start_time, status, is_default';
function requireSupabase(){const s=getSupabaseClient();if(!s)throw new Error('Supabaseの環境変数が設定されていません。');return s;}
function scope<T extends {eq:(c:string,v:any)=>T;is:(c:string,v:null)=>T}>(q:T,branchId:string|null):T{return branchId?q.eq('branch_id',branchId):q.is('branch_id',null);}
function toPhaseSummary(r:PhaseRow):PhaseSummary{return{id:r.id,routeId:r.route_id,branchId:r.branch_id??null,name:r.name,description:r.description,orderValue:Number(r.order_value),startTime:r.start_time,status:r.status,isDefault:r.is_default};}
function phaseTimeMinutes(value:string|null):number|null{if(!value)return null;const match=value.match(/^(\d{1,2}):(\d{2})/);if(!match)return null;const hours=Number(match[1]),minutes=Number(match[2]);return Number.isFinite(hours)&&Number.isFinite(minutes)?hours*60+minutes:null;}
function comparePhasesByTime(a:PhaseSummary,b:PhaseSummary):number{const at=phaseTimeMinutes(a.startTime),bt=phaseTimeMinutes(b.startTime);if(at!==null&&bt!==null&&at!==bt)return at-bt;if(at!==null&&bt===null)return-1;if(at===null&&bt!==null)return 1;return a.orderValue-b.orderValue;}
export async function normalizeRoutePhaseOrder(routeId:string,branchId:string|null=null):Promise<PhaseSummary[]>{const s=requireSupabase();const phases=(await getRoutePhases(routeId,branchId)).slice().sort(comparePhasesByTime);const normalized=phases.map((phase,index)=>({...phase,orderValue:(index+1)*1000}));const changed=normalized.filter((phase,index)=>phase.orderValue!==phases[index].orderValue);if(changed.length){await Promise.all(changed.map(async phase=>{let q=s.from('phases').update({order_value:phase.orderValue}).eq('id',phase.id).eq('route_id',routeId);q=scope(q,branchId);const{error}=await q.is('deleted_at',null);if(error)throw error;}));}return normalized;}
export async function getRoutePhases(routeId:string,branchId:string|null=null):Promise<PhaseSummary[]>{if(!routeId)return[];let q=requireSupabase().from('phases').select(phaseColumns).eq('route_id',routeId);q=scope(q,branchId);const{data,error}=await q.is('deleted_at',null).order('order_value',{ascending:true}).order('created_at',{ascending:true});if(error)throw error;return((data??[])as PhaseRow[]).map(toPhaseSummary);}
export async function createRoutePhase(routeId:string,input:CreatePhaseInput,branchId:string|null=null):Promise<PhaseSummary>{if(!routeId)throw new Error('Route IDがありません。');const name=input.name.trim();if(!name)throw new Error('Phase名を入力してください。');if(name.length>40)throw new Error('Phase名は40文字以内で入力してください。');const s=requireSupabase();let oq=s.from('phases').select('order_value').eq('route_id',routeId);oq=scope(oq,branchId);const{data:lastRows,error:orderError}=await oq.is('deleted_at',null).order('order_value',{ascending:false}).limit(1);if(orderError)throw orderError;const last=lastRows?.length?Number(lastRows[0].order_value):0;const{data,error}=await s.from('phases').insert({route_id:routeId,branch_id:branchId,name,description:input.description?.trim()||null,start_time:input.startTime||null,order_value:Number.isFinite(last)?last+1000:1000,status:'planned',is_optional:false,is_default:false}).select(phaseColumns).single();if(error)throw error;const created=toPhaseSummary(data as PhaseRow);const normalized=await normalizeRoutePhaseOrder(routeId,branchId);return normalized.find(phase=>phase.id===created.id)??created;}
export async function updateRoutePhase(routeId:string,phaseId:string,input:UpdatePhaseInput,branchId:string|null=null):Promise<PhaseSummary>{if(!routeId||!phaseId)throw new Error('Phaseを確認できませんでした。');const s=requireSupabase();let cq=s.from('phases').select('is_default').eq('id',phaseId).eq('route_id',routeId);cq=scope(cq,branchId);const{data:current,error:currentError}=await cq.is('deleted_at',null).single();if(currentError)throw currentError;const name=input.name.trim();if(!current?.is_default&&!name)throw new Error('Phase名を入力してください。');if(name.length>40)throw new Error('Phase名は40文字以内で入力してください。');let uq=s.from('phases').update({name,description:input.description?.trim()||null,start_time:input.startTime||null}).eq('id',phaseId).eq('route_id',routeId);uq=scope(uq,branchId);const{data,error}=await uq.is('deleted_at',null).select(phaseColumns).single();if(error)throw error;const updated=toPhaseSummary(data as PhaseRow);const normalized=await normalizeRoutePhaseOrder(routeId,branchId);return normalized.find(phase=>phase.id===updated.id)??updated;}
export async function deleteRoutePhase(routeId:string,phaseId:string,branchId:string|null=null):Promise<void>{if(!routeId||!phaseId)throw new Error('Phaseを特定できません。');const{error}=await requireSupabase().rpc('delete_route_phase',{p_route_id:routeId,p_phase_id:phaseId,p_branch_id:branchId});if(error){const code=String((error as {code?:unknown}).code??'');const message=String((error as {message?:unknown}).message??'');if(code==='23514'||/last phase cannot be deleted/i.test(message))throw new Error(branchId ? 'サブRouteのPhaseを削除できませんでした。' : '最後のPhaseは削除できません。');throw error;}await normalizeRoutePhaseOrder(routeId,branchId);}
